### ISSUE TITLE
Number of retries not accurate (Single Choice Set in Column)

### ISSUE THREAD

**Issue by tammets** [centre-for-educational-technology/vara#185]
https://vara.h5p.ee/instructional-trajectory-session/6/participate

**Comment by pjotrsavitski** [comment]
This seems to be due to the fact that every time a question in the set is answered, the `completed` statement for the whole column is being sent. This means that multiple completed statements for the column are sent, thus the retry count can not be meaningfully determined without going through all the statements and determining which ones should be taken into account. I currently see not way to to solve it unless there is a difference between the final `completed` statement and intermittent ones.

**Comment by pjotrsavitski** [comment]
The issue has been identified and [here](https://github.com/h5p/h5p-column/pull/65) is a simple yet not very elegant solution to the problem. The catch is with the need to applying manually and then on every version change.

**Comment by pjotrsavitski** [comment]
Closing the issue as the patch has resolved it and there is not way for us to make sure that Pull Request gets accepted and a new version released by the Joubel team.
