### ISSUE TITLE
Brancining scenario preview is not loading for Estonian & Russian

### ISSUE THREAD

**Issue by tammets** [centre-for-educational-technology/vara#24]
![2022-10-30 09 49 57](https://user-images.githubusercontent.com/380007/198868094-c7bf0ecb-80b0-4f4a-af9d-f70bfb533122.gif)

**Comment by pjotrsavitski** [comment]
Seems to be an issue with extracting translation for the fields. My guess is that it is because the content type does not have translations to Russian and Estonian. Code has to be checked for more details.

<img width="1313" alt="Screenshot 2022-10-30 at 17 35 08" src="https://user-images.githubusercontent.com/518331/198887442-6e111d4c-673c-4e03-bc46-57e78f1ba0ba.png">

**Comment by tammets** [comment]
https://github.com/h5p/h5p-branching-scenario/blob/master/language/et.json ?

**Comment by pjotrsavitski** [comment]
This was an issue with translation files for Interactive Video version 1.24.2 or maybe even earlier, that got fixed in versions 1.24.3 and 1.24.4. See the [diff](https://github.com/h5p/h5p-interactive-video/compare/1.24.2...1.24.4) for more details.

Updating the content library fixed the issue.
